# Generated by Django 5.0.10 on 2024-12-29 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelToDb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('excel_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='databaseinfo', to='excelToDb.excelupload')),
            ],
        ),
    ]
