# Generated by Django 5.0.10 on 2024-12-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelToDb', '0002_databaseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
