# Generated by Django 5.0.10 on 2024-12-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelToDb', '0003_alter_databaseinfo_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinfo',
            name='database_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
