# Generated by Django 5.0.10 on 2024-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelToDb', '0004_databaseinfo_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='server_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
