# Generated by Django 5.0.10 on 2024-12-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelToDb', '0005_alter_databaseinfo_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='database_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
